#cloud-config
# https://cloudinit.readthedocs.io/en/latest/topics/examples.html#yaml-examples
# aws ec2 get-launch-template-data --instance-id i-02ea7780e67af51cc --query 'LaunchTemplateData' | jq '.UserData' | base64 -di | gzip -d -c
packages: null
runcmd:
- - /var/lib/cloud/scripts/per-instance/bootstrap.al2.sh
write_files:
- content: |
    # eksctl-specific systemd drop-in unit for kubelet, for Amazon Linux 2 (AL2)

    [Service]
    # Local metadata parameters: REGION, AWS_DEFAULT_REGION
    EnvironmentFile=/etc/eksctl/metadata.env
    # Global and static parameters: CLUSTER_DNS, NODE_LABELS, NODE_TAINTS
    EnvironmentFile=/etc/eksctl/kubelet.env
    # Local non-static parameters: NODE_IP, INSTANCE_ID
    EnvironmentFile=/etc/eksctl/kubelet.local.env

    ExecStart=
    ExecStart=/usr/bin/kubelet \
      --node-ip=${NODE_IP} \
      --node-labels=${NODE_LABELS},alpha.eksctl.io/instance-id=${INSTANCE_ID} \
      --max-pods=${MAX_PODS} \
      --register-node=true --register-with-taints=${NODE_TAINTS} \
      --allow-privileged=true \
      --cloud-provider=aws \
      --container-runtime=docker \
      --network-plugin=cni \
      --cni-bin-dir=/opt/cni/bin \
      --cni-conf-dir=/etc/cni/net.d \
      --pod-infra-container-image=${AWS_EKS_ECR_ACCOUNT}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/eks/pause-amd64:3.1 \
      --kubeconfig=/etc/eksctl/kubeconfig.yaml \
      --config=/etc/eksctl/kubelet.yaml
  owner: root:root
  path: /etc/systemd/system/kubelet.service.d/10-eksclt.al2.conf
  permissions: "0644"
- content: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /etc/eksctl/ca.crt
        server: https://D4F844AF3C8CA49E513A62D11866F07A.gr7.us-west-2.eks.amazonaws.com
      name: janitha-eks-114-2.us-west-2.eksctl.io
    contexts:
    - context:
        cluster: janitha-eks-114-2.us-west-2.eksctl.io
        user: kubelet@janitha-eks-114-2.us-west-2.eksctl.io
      name: kubelet@janitha-eks-114-2.us-west-2.eksctl.io
    current-context: kubelet@janitha-eks-114-2.us-west-2.eksctl.io
    kind: Config
    preferences: {}
    users:
    - name: kubelet@janitha-eks-114-2.us-west-2.eksctl.io
      user:
        exec:
          apiVersion: client.authentication.k8s.io/v1alpha1
          args:
          - token
          - -i
          - janitha-eks-114-2
          command: aws-iam-authenticator
          env: null
  owner: root:root
  path: /etc/eksctl/kubeconfig.yaml
  permissions: "0644"
- content: |
    g3.16xlarge 452
    m5.xlarge 58
    m5ad.2xlarge 58
    m5d.4xlarge 234
    r4.2xlarge 58
    a1.medium 8
    c5n.18xlarge 737
    m1.small 8
    m5d.16xlarge 737
    r5ad.large 29
    c4.8xlarge 234
    p3dn.24xlarge 737
    r5.large 29
    r5ad.4xlarge 234
    z1d.3xlarge 234
    i3.4xlarge 234
    t3.2xlarge 58
    m1.xlarge 58
    r5.16xlarge 737
    z1d.2xlarge 58
    g4dn.4xlarge 29
    hs1.8xlarge 234
    m1.large 29
    i3.8xlarge 234
    m5d.12xlarge 234
    r5a.16xlarge 737
    z1d.xlarge 58
    g4dn.2xlarge 29
    m5d.8xlarge 234
    r5d.12xlarge 234
    m5a.large 29
    m5d.metal 737
    c3.large 29
    m2.2xlarge 118
    m3.2xlarge 118
    r3.4xlarge 234
    r5.24xlarge 737
    r5d.xlarge 58
    u-6tb1.metal 147
    c4.large 29
    i3en.xlarge 58
    r5ad.2xlarge 58
    t2.medium 17
    t3.xlarge 58
    c5.18xlarge 737
    m4.xlarge 58
    r3.xlarge 58
    r4.8xlarge 234
    r4.xlarge 58
    c1.medium 12
    c4.2xlarge 58
    d2.4xlarge 234
    m5a.16xlarge 737
    r5d.16xlarge 737
    r5d.large 29
    g4dn.metal 737
    m5.large 29
    r5.metal 737
    r5d.4xlarge 234
    t3a.medium 17
    r4.large 29
    t3a.micro 4
    z1d.12xlarge 737
    c5n.2xlarge 58
    i3.large 29
    r3.8xlarge 234
    c5d.large 29
    m5ad.12xlarge 234
    t2.micro 4
    t3.nano 4
    c3.2xlarge 58
    h1.2xlarge 58
    i3en.12xlarge 234
    r5.8xlarge 234
    t2.2xlarge 44
    x1e.4xlarge 58
    c5.large 29
    c5d.xlarge 58
    i2.xlarge 58
    m4.10xlarge 234
    t3.medium 17
    c5.xlarge 58
    f1.2xlarge 58
    m5.4xlarge 234
    m5a.2xlarge 58
    r5a.8xlarge 234
    m5a.12xlarge 234
    f1.4xlarge 234
    i3.xlarge 58
    m5.metal 737
    t3a.2xlarge 58
    u-12tb1.metal 147
    c5.24xlarge 737
    g3.8xlarge 234
    h1.8xlarge 234
    m4.2xlarge 58
    r5.2xlarge 58
    c5d.4xlarge 234
    p3.16xlarge 234
    r5.12xlarge 234
    r5.xlarge 58
    a1.xlarge 58
    g2.8xlarge 234
    i3.16xlarge 452
    t3a.nano 4
    d2.2xlarge 58
    g3.4xlarge 234
    i3en.6xlarge 234
    t3a.large 35
    i3.2xlarge 58
    m5a.8xlarge 234
    m2.xlarge 58
    m5.2xlarge 58
    r4.16xlarge 452
    r4.4xlarge 234
    c5.9xlarge 234
    g2.2xlarge 58
    i3en.large 29
    t1.micro 4
    r5a.12xlarge 234
    t3a.small 8
    p3.2xlarge 58
    x1e.8xlarge 58
    z1d.metal 737
    h1.16xlarge 452
    i2.8xlarge 234
    m5.24xlarge 737
    a1.4xlarge 234
    g4dn.16xlarge 58
    m2.4xlarge 234
    m5a.xlarge 58
    z1d.large 29
    m5d.large 29
    m5d.xlarge 58
    u-9tb1.metal 147
    m4.large 20
    m5.16xlarge 737
    r5d.metal 737
    z1d.6xlarge 234
    c5d.9xlarge 234
    i3en.24xlarge 737
    t3.large 35
    a1.2xlarge 58
    c5n.large 29
    d2.xlarge 58
    cc2.8xlarge 234
    g3s.xlarge 58
    m5ad.24xlarge 737
    c5.4xlarge 234
    c5.metal 737
    x1.16xlarge 234
    p2.16xlarge 234
    c4.4xlarge 234
    m5ad.xlarge 58
    r5a.xlarge 58
    x1.32xlarge 234
    x1e.xlarge 29
    c4.xlarge 58
    g4dn.8xlarge 58
    m3.xlarge 58
    g4dn.12xlarge 234
    m5ad.large 29
    t2.nano 4
    t3.micro 4
    x1e.32xlarge 234
    i2.4xlarge 234
    m5a.24xlarge 737
    r3.large 29
    g4dn.xlarge 29
    i3en.2xlarge 58
    m5ad.4xlarge 234
    m4.4xlarge 234
    c1.xlarge 58
    c5.12xlarge 234
    m3.medium 12
    r5ad.12xlarge 234
    r5d.24xlarge 737
    r5d.8xlarge 234
    t2.small 11
    c5.2xlarge 58
    m5d.24xlarge 737
    r5a.24xlarge 737
    t3a.xlarge 58
    c3.4xlarge 234
    c3.xlarge 58
    c5n.9xlarge 234
    t2.large 35
    x1e.16xlarge 234
    c5n.xlarge 58
    f1.16xlarge 242
    p2.8xlarge 234
    p3.8xlarge 234
    r5a.2xlarge 58
    r5ad.24xlarge 737
    r5ad.xlarge 58
    c3.8xlarge 234
    c5n.4xlarge 234
    cr1.8xlarge 234
    m4.16xlarge 234
    c5d.2xlarge 58
    h1.4xlarge 234
    r5a.large 29
    d2.8xlarge 234
    i3.metal 737
    i3en.3xlarge 58
    c5d.18xlarge 737
    i2.2xlarge 58
    p2.xlarge 58
    m1.medium 12
    m3.large 29
    m5.8xlarge 234
    r5.4xlarge 234
    r5d.2xlarge 58
    x1e.2xlarge 58
    r5a.4xlarge 234
    a1.large 29
    m5.12xlarge 234
    m5a.4xlarge 234
    m5d.2xlarge 58
    r3.2xlarge 58
    t2.xlarge 44
    t3.small 11
  owner: root:root
  path: /etc/eksctl/max_pods.map
  permissions: "0644"
- content: |-
    AWS_DEFAULT_REGION=us-west-2
    AWS_EKS_CLUSTER_NAME=janitha-eks-114-2
    AWS_EKS_ENDPOINT=https://D4F844AF3C8CA49E513A62D11866F07A.gr7.us-west-2.eks.amazonaws.com
    AWS_EKS_ECR_ACCOUNT=602401143452
  owner: root:root
  path: /etc/eksctl/metadata.env
  permissions: "0644"
- content: |-
    NODE_LABELS=alpha.eksctl.io/cluster-name=janitha-eks-114-2,alpha.eksctl.io/nodegroup-name=standard-workers
    NODE_TAINTS=
  owner: root:root
  path: /etc/eksctl/kubelet.env
  permissions: "0644"
- content: |
    address: 0.0.0.0
    apiVersion: kubelet.config.k8s.io/v1beta1
    authentication:
      anonymous:
        enabled: false
      webhook:
        cacheTTL: 2m0s
        enabled: true
      x509:
        clientCAFile: /etc/eksctl/ca.crt
    authorization:
      mode: Webhook
      webhook:
        cacheAuthorizedTTL: 5m0s
        cacheUnauthorizedTTL: 30s
    cgroupDriver: cgroupfs
    clusterDNS:
    - 10.100.0.10
    clusterDomain: cluster.local
    featureGates:
      RotateKubeletServerCertificate: true
    kind: KubeletConfiguration
    serverTLSBootstrap: true
  owner: root:root
  path: /etc/eksctl/kubelet.yaml
  permissions: "0644"
- content: |
    -----BEGIN CERTIFICATE-----
    MIICyDCCAbCgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
    cm5ldGVzMB4XDTE5MTAyODIyMDg1NloXDTI5MTAyNTIyMDg1NlowFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALs2
    9vwDtIR713SiEbW/4hEn73nEFTMzxczMKqPq0BDbnr8cr48AeNbBg+h/SW0ctp1B
    faFo68kdi2Bm1s+624AyUs14L7n4tfkmhkhnazNgjTwg+SNWEnhfZd/OJLgwTQxM
    nsLiXHJbZngcTuVxMTv9KEruuAUzKClgVyVPfofhDzcWXfqG/nbGAU+R0Jbf71Nt
    RhSMQXtpnEBy5Oq8/MFW+2kwXlQhTVrA9msL11w1H/rWdyjrrUVOXtE1QDS/5K7u
    sQSPSPHPTv1X6hW44q7T0oiWB3wJQWKpMrkakbdoy037D4vIdpz4P8PX79JcWNp0
    qhaR/lAPa/FokL364xkCAwEAAaMjMCEwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB
    /wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAGkGm7JJYE9HFPVBCla7huxL5bZl
    URMILvXDMh+VcW6Z/11yQnxPRlaMDXvNbZqslu7uOAsevLXrk8WKq8Y829hNqudw
    +Xb6kRQy+81z/FpVZkBQyw4Lq+XvPciFSyeyq1faqNTrFy2V6z4X5c0M29OIITb3
    P5xIW4mEUvmyUhYPgi+/kZHKRppQYFJ+x12CSjLtPgBIm2fzq4BN/K3uUBNF0DSh
    vV/oGKlJpOuYOAZL2PQrKZAvQtbI0tk9yw2o6VeHakHDvqFtO3LlyZKd9dI37MWJ
    NMvfmmHt4ZJT+NfuUAJkykpUbj2aA0ve91wnROow0TDou+D27Y3eMT4cH/Y=
    -----END CERTIFICATE-----
  owner: root:root
  path: /etc/eksctl/ca.crt
  permissions: "0644"
- content: |
    #!/bin/bash

    set -o errexit
    set -o pipefail
    set -o nounset

    function get_max_pods() {
      while read instance_type pods; do
        if  [[ "${instance_type}" == "${1}" ]] && [[ "${pods}" =~ ^[0-9]+$ ]] ; then
          echo ${pods}
          return
        fi
      done < /etc/eksctl/max_pods.map
    }

    NODE_IP="$(curl --silent http://169.254.169.254/latest/meta-data/local-ipv4)"
    INSTANCE_ID="$(curl --silent http://169.254.169.254/latest/meta-data/instance-id)"
    INSTANCE_TYPE="$(curl --silent http://169.254.169.254/latest/meta-data/instance-type)"

    source /etc/eksctl/kubelet.env # this can override MAX_PODS

    cat > /etc/eksctl/kubelet.local.env <<EOF
    NODE_IP=${NODE_IP}
    INSTANCE_ID=${INSTANCE_ID}
    INSTANCE_TYPE=${INSTANCE_TYPE}
    MAX_PODS=${MAX_PODS:-$(get_max_pods "${INSTANCE_TYPE}")}
    EOF

    systemctl daemon-reload
    systemctl enable kubelet
    systemctl start kubelet
  owner: root:root
  path: /var/lib/cloud/scripts/per-instance/bootstrap.al2.sh
  permissions: "0755"
